package io.github.kroha22.tempo.model



// Generated from kroha22/tempo-react de007e53fca4b94f1ac098c7468ccd1955dcffc2.

data class NativeWord(val id: String, val portuguese: String, val russian: String, val example: String = "")

data class NativeSet(val id: String, val title: String, val wordIds: List<String>)

data class NativeTopic(val id: String, val title: String, val sets: List<NativeSet>)

data class NativeActivity(val id: String, val prompt: String, val before: String, val after: String, val options: List<AnswerOption>, val correctOptionId: String, val feedback: String)

data class NativeUsage(val id: String, val title: String, val situation: String, val collectionIds: List<String>, val examples: List<Example>, val exercises: List<NativeActivity>)

data class NativeRelatedLesson(val id: String, val title: String, val cue: String, val examples: List<Example>, val vocabulary: List<Example>, val activity: NativeActivity)

data class NativeVerbForms(val key: String, val title: String, val translation: String, val forms: List<String>)



val nativeWords = listOf(
    NativeWord("scene-word:a-casa", "a casa", "Дом", ""),
    NativeWord("scene-word:a-escola", "a escola", "Школа", ""),
    NativeWord("scene-word:a-loja", "a loja", "Магазин", ""),
    NativeWord("scene-word:a-farmacia", "a farmácia", "Аптека", ""),
    NativeWord("scene-word:o-cafe", "o café", "Кафе", ""),
    NativeWord("scene-word:a-rua", "a rua", "Улица", ""),
    NativeWord("scene-word:o-autocarro", "o autocarro", "Автобус", ""),
    NativeWord("scene-word:a-paragem", "a paragem", "Остановка", ""),
    NativeWord("scene-word:o-barco", "o barco", "Лодка", ""),
    NativeWord("scene-word:o-mar", "o mar", "Море", ""),
    NativeWord("scene-word:o-guarda-sol", "o guarda-sol", "Пляжный зонт", ""),
    NativeWord("scene-word:a-areia", "a areia", "Песок", ""),
    NativeWord("scene-word:o-balde", "o balde", "Ведро", ""),
    NativeWord("scene-word:a-toalha", "a toalha", "Полотенце", ""),
    NativeWord("scene-word:a-arvore", "a árvore", "Дерево", ""),
    NativeWord("scene-word:a-borboleta", "a borboleta", "Бабочка", ""),
    NativeWord("scene-word:a-abelha", "a abelha", "Пчела", ""),
    NativeWord("scene-word:a-flor", "a flor", "Цветок", ""),
    NativeWord("scene-word:o-caracol", "o caracol", "Улитка", ""),
    NativeWord("scene-word:a-folha", "a folha", "Лист", ""),
    NativeWord("scene-word:a-relva", "a relva", "Трава", ""),
    NativeWord("scene-word:a-nuvem", "a nuvem", "Облако", ""),
    NativeWord("scene-word:a-chuva", "a chuva", "Дождь", ""),
    NativeWord("scene-word:o-vento", "o vento", "Ветер", ""),
    NativeWord("scene-word:o-guarda-chuva", "o guarda-chuva", "Зонт", ""),
    NativeWord("scene-word:o-casaco", "o casaco", "Куртка", ""),
    NativeWord("scene-word:as-botas", "as botas", "Сапоги", ""),
    NativeWord("scene-word:a-poca", "a poça", "Лужа", ""),
    NativeWord("scene-word:a-vaca", "a vaca", "Корова", ""),
    NativeWord("scene-word:o-cavalo", "o cavalo", "Лошадь", ""),
    NativeWord("scene-word:o-gato", "o gato", "Кот", ""),
    NativeWord("scene-word:o-porco", "o porco", "Свинья", ""),
    NativeWord("scene-word:a-ovelha", "a ovelha", "Овца", ""),
    NativeWord("scene-word:a-galinha", "a galinha", "Курица", ""),
    NativeWord("scene-word:o-pato", "o pato", "Утка", ""),
    NativeWord("scene-word:a-maca", "a maçã", "Яблоко", ""),
    NativeWord("scene-word:a-banana", "a banana", "Банан", ""),
    NativeWord("scene-word:a-laranja", "a laranja", "Апельсин", ""),
    NativeWord("scene-word:a-cesta", "a cesta", "Корзина", ""),
    NativeWord("scene-word:o-tomate", "o tomate", "Помидор", ""),
    NativeWord("scene-word:a-batata", "a batata", "Картофель", ""),
    NativeWord("scene-word:a-cenoura", "a cenoura", "Морковь", ""),
    NativeWord("scene-word:a-mochila", "a mochila", "Рюкзак", ""),
    NativeWord("scene-word:o-caderno", "o caderno", "Тетрадь", ""),
    NativeWord("scene-word:o-lapis", "o lápis", "Карандаш", ""),
    NativeWord("scene-word:a-caneta", "a caneta", "Ручка", ""),
    NativeWord("scene-word:o-livro", "o livro", "Книга", ""),
    NativeWord("scene-word:a-borracha", "a borracha", "Ластик", ""),
    NativeWord("scene-word:a-regua", "a régua", "Линейка", ""),
    NativeWord("scene-word:a-cadeira", "a cadeira", "Стул", ""),
    NativeWord("scene-word:o-leite", "o leite", "Молоко", ""),
    NativeWord("scene-word:o-pao", "o pão", "Хлеб", ""),
    NativeWord("scene-word:a-mesa", "a mesa", "Стол", ""),
    NativeWord("scene-word:o-prato", "o prato", "Тарелка", ""),
    NativeWord("scene-word:a-chavena", "a chávena", "Чашка", ""),
    NativeWord("scene-word:a-colher", "a colher", "Ложка", ""),
    NativeWord("scene-word:o-ovo", "o ovo", "Яйцо", ""),
    NativeWord("scene-word:o-parque", "o parque", "Парк", ""),
    NativeWord("scene-word:o-passaro", "o pássaro", "Птица", ""),
    NativeWord("scene-word:o-banco", "o banco", "Скамейка", ""),
    NativeWord("scene-word:a-bicicleta", "a bicicleta", "Велосипед", ""),
    NativeWord("scene-word:o-cao", "o cão", "Собака", ""),
    NativeWord("scene-word:a-bola", "a bola", "Мяч", ""),
    NativeWord("clothing-camisola", "a camisola", "Джемпер", ""),
    NativeWord("clothing-casaco", "o casaco", "Куртка", ""),
    NativeWord("clothing-cachecol", "o cachecol", "Шарф", ""),
    NativeWord("clothing-calcas", "as calças", "Брюки", ""),
    NativeWord("clothing-calcoes", "os calções", "Шорты", ""),
    NativeWord("clothing-saia", "a saia", "Юбка", ""),
    NativeWord("clothing-pijama", "o pijama", "Пижама", ""),
    NativeWord("clothing-blusa", "a blusa", "Блузка", ""),
    NativeWord("clothing-vestido", "o vestido", "Платье", ""),
    NativeWord("clothing-sapatos", "os sapatos", "Туфли", ""),
    NativeWord("study:chunk:ola", "Olá!", "Привет! / Здравствуйте!", ""),
    NativeWord("study:chunk:como-te-chamas", "Como te chamas?", "Как тебя зовут?", ""),
    NativeWord("study:chunk:chamo-me", "Chamo-me ...", "Меня зовут ...", ""),
    NativeWord("study:chunk:sou-name", "Sou ...", "Я ...", ""),
    NativeWord("study:chunk:muito-prazer", "Muito prazer.", "Очень приятно.", ""),
    NativeWord("study:verb:ser:identity", "ser", "быть: идентичность или характеристика", ""),
    NativeWord("study:verb:estar:state", "estar", "быть: состояние сейчас", ""),
    NativeWord("study:chunk:onde-esta", "Onde está...?", "Где находится...?", ""),
    NativeWord("study:chunk:dentro-de", "dentro de", "внутри", ""),
    NativeWord("study:chunk:em-cima-de", "em cima de", "на / сверху", ""),
    NativeWord("study:chunk:debaixo-de", "debaixo de", "под", ""),
    NativeWord("study:chunk:ao-lado-de", "ao lado de", "рядом с", ""),
    NativeWord("study:verb:ter:possession", "ter", "иметь", ""),
    NativeWord("study:chunk:ha-presence", "Há uma...", "Есть...", ""),
    NativeWord("study:verb:ficar:location", "ficar", "находиться, быть расположенным", ""),
    NativeWord("study:chunk:onde-fica", "Onde fica...?", "Где расположено...?", ""),
    NativeWord("study:noun:mesa", "a mesa", "стол", ""),
    NativeWord("study:noun:caixa", "a caixa", "коробка", ""),
    NativeWord("study:noun:porta", "a porta", "дверь", ""),
    NativeWord("study:noun:janela", "a janela", "окно", ""),
    NativeWord("study:noun:gato", "o gato", "кот", ""),
    NativeWord("study:noun:chave", "a chave", "ключ", ""),
    NativeWord("study:noun:livro", "o livro", "книга", ""),
    NativeWord("study:noun:sala", "a sala", "комната / гостиная", ""),
    NativeWord("study:noun:cadeira", "a cadeira", "стул", ""),
    NativeWord("study:noun:cama", "a cama", "кровать", ""),
    NativeWord("study:noun:quarto", "o quarto", "спальня", ""),
    NativeWord("study:noun:armario", "o armário", "шкаф", ""),
    NativeWord("study:noun:copo", "o copo", "стакан", ""),
    NativeWord("study:noun:estacao", "a estação", "станция", ""),
    NativeWord("study:noun:hotel", "o hotel", "отель", ""),
    NativeWord("study:noun:farmacia", "a farmácia", "аптека", ""),
    NativeWord("study:noun:centro", "o centro", "центр", ""),
    NativeWord("house-telhado", "o telhado", "Крыша", ""),
    NativeWord("house-chamine", "a chaminé", "Дымоход, дымовая труба", ""),
    NativeWord("house-janela", "a janela", "Окно", ""),
    NativeWord("house-cortina", "a cortina", "Штора", ""),
    NativeWord("house-persiana", "a persiana", "Жалюзи", ""),
    NativeWord("house-varanda", "a varanda", "Балкон", ""),
    NativeWord("house-quarto", "o quarto", "Спальня", ""),
    NativeWord("house-casa-de-banho", "a casa de banho", "Ванная комната", ""),
    NativeWord("house-sala", "a sala", "Гостиная", ""),
    NativeWord("house-cozinha", "a cozinha", "Кухня", ""),
    NativeWord("house-escritorio", "o escritório", "Рабочий кабинет", ""),
    NativeWord("house-escada", "as escadas", "Лестница", ""),
    NativeWord("house-corrimao", "o corrimão", "Перила, поручень", ""),
    NativeWord("house-hall-de-entrada", "o hall de entrada", "Прихожая", ""),
    NativeWord("house-res-do-chao", "o rés do chão", "Первый этаж, на уровне земли", ""),
    NativeWord("house-primeiro-andar", "o primeiro andar", "Второй этаж по русской нумерации", ""),
    NativeWord("house-sotao", "o sótão", "Чердак", ""),
    NativeWord("house-cave", "a cave", "Подвал", ""),
    NativeWord("house-garagem", "a garagem", "Гараж", ""),
    NativeWord("house-grelhador", "o grelhador", "Гриль, мангал", ""),
    NativeWord("house-teto", "o teto", "Потолок", ""),
    NativeWord("house-relva", "a relva", "Газон, трава", ""),
    NativeWord("house-lareira", "a lareira", "Камин", ""),
    NativeWord("house-guarda-sol", "o guarda-sol", "Солнцезащитный зонт", ""),
    NativeWord("house-jardim", "o jardim", "Сад", ""),
    NativeWord("house-mesa-de-cabeceira", "a mesa de cabeceira", "Прикроватная тумбочка", ""),
    NativeWord("house-mesa-de-jardim", "a mesa de jardim", "Садовый стол", ""),
    NativeWord("house-guarda-fatos", "o guarda-fatos", "Шкаф для одежды", ""),
    NativeWord("house-cama", "a cama", "Кровать", ""),
    NativeWord("house-tapete", "o tapete", "Ковёр", ""),
    NativeWord("house-secretaria", "a secretária", "Письменный стол", ""),
    NativeWord("house-tacho", "o tacho", "Кастрюля", ""),
    NativeWord("house-talheres", "os talheres", "Столовые приборы", ""),
    NativeWord("house-chuveiro", "o chuveiro", "Душ", ""),
    NativeWord("house-lava-louca", "o lava-louça", "Кухонная мойка", ""),
    NativeWord("house-cadeiras", "as cadeiras", "Стулья", ""),
    NativeWord("house-mesa", "a mesa", "Стол", ""),
    NativeWord("house-sofa", "o sofá", "Диван", ""),
    NativeWord("house-televisao", "a televisão", "Телевизор", ""),
    NativeWord("house-aparelhagem", "a aparelhagem", "Музыкальный центр", ""),
    NativeWord("house-comoda", "a cómoda", "Комод", ""),
    NativeWord("house-sanita", "a sanita", "Унитаз", ""),
    NativeWord("house-estante-de-livros", "a estante de livros", "Книжный стеллаж", ""),
    NativeWord("house-carro", "o carro", "Машина", ""),
    NativeWord("house-bicicleta", "a bicicleta", "Велосипед", ""),
    NativeWord("house-caixa-de-ferramentas", "a caixa de ferramentas", "Ящик с инструментами", ""),
    NativeWord("house-trotinete", "a trotinete", "Самокат", ""),
    NativeWord("house-toalha", "a toalha", "Полотенце", ""),
    NativeWord("house-espelho", "o espelho", "Зеркало", ""),
    NativeWord("house-prato", "o prato", "Тарелка", ""),
    NativeWord("house-banheira", "a banheira", "Ванна", ""),
    NativeWord("v0083", "ler", "читать", ""),
    NativeWord("v0062", "escrever", "писать", ""),
    NativeWord("v0242", "completar", "дополнять", ""),
    NativeWord("v0258", "ligar", "соединять", ""),
    NativeWord("v0682", "assinalar", "отмечать", ""),
    NativeWord("v0379", "pintar", "раскрашивать", ""),
    NativeWord("v0154", "escolher", "выбирать", ""),
    NativeWord("v0091", "responder", "отвечать", ""),
    NativeWord("v0005", "fazer", "делать", ""),
    NativeWord("v0006", "ir", "идти; ехать", ""),
    NativeWord("v0011", "saber", "знать; уметь", ""),
    NativeWord("v0012", "querer", "хотеть", ""),
    NativeWord("v0016", "vir", "приходить", ""),
    NativeWord("v0017", "chegar", "прибывать; доходить", ""),
    NativeWord("v0018", "falar", "говорить", ""),
    NativeWord("v0020", "encontrar", "находить; встречать", ""),
    NativeWord("v0021", "levar", "нести; отвозить", ""),
    NativeWord("v0024", "pensar", "думать", ""),
    NativeWord("v0029", "sair", "выходить", ""),
    NativeWord("v0030", "voltar", "возвращаться", ""),
    NativeWord("v0034", "sentir", "чувствовать", ""),
    NativeWord("v0035", "entrar", "входить", ""),
    NativeWord("v0036", "chamar", "звать; называть", ""),
    NativeWord("v0042", "ouvir", "слышать; слушать", ""),
    NativeWord("v0047", "andar", "ходить", ""),
    NativeWord("v0048", "trabalhar", "работать", ""),
    NativeWord("v0050", "pedir", "просить; заказывать", ""),
    NativeWord("v0057", "gostar", "нравиться; любить", ""),
    NativeWord("v0058", "usar", "использовать", ""),
    NativeWord("v0061", "abrir", "открывать", ""),
    NativeWord("v0066", "lembrar", "помнить; напоминать", ""),
    NativeWord("v0067", "trazer", "приносить", ""),
    NativeWord("v0068", "procurar", "искать", ""),
    NativeWord("v0075", "correr", "бежать", ""),
    NativeWord("v0079", "pagar", "платить", ""),
    NativeWord("v0081", "entender", "понимать; понять", ""),
    NativeWord("v0085", "perguntar", "спрашивать", ""),
    NativeWord("v0094", "explicar", "объяснять", ""),
    NativeWord("v0099", "estudar", "учиться; изучать", ""),
    NativeWord("v0102", "parar", "останавливаться", ""),
    NativeWord("v0106", "fechar", "закрывать", ""),
    NativeWord("v0114", "subir", "подняться", ""),
    NativeWord("v0123", "comer", "есть", ""),
    NativeWord("v0124", "vender", "продавать", ""),
    NativeWord("v0126", "comprar", "купить; покупать", ""),
    NativeWord("v0135", "ajudar", "помогать", ""),
    NativeWord("v0142", "esquecer", "забывать", ""),
    NativeWord("v0153", "rir", "смеяться", ""),
    NativeWord("v0157", "descer", "спуститься", ""),
    NativeWord("v0158", "dormir", "спать", ""),
    NativeWord("v0196", "sorrir", "улыбаться; улыбнуться", ""),
    NativeWord("v0218", "cozinhar", "готовить еду", ""),
    NativeWord("v0270", "beber", "пить", ""),
    NativeWord("v0294", "acordar", "просыпаться", ""),
    NativeWord("v0297", "viajar", "путешествовать", ""),
    NativeWord("v0340", "ensinar", "учить", ""),
    NativeWord("v0432", "dançar", "танцевать", ""),
    NativeWord("v0522", "descansar", "отдыхать", ""),
    NativeWord("v0523", "passear", "гулять", ""),
    NativeWord("v0960", "nadar", "плавать; плыть", ""),
    NativeWord("general-vocabulary:noun:apartamento", "o apartamento", "квартира", ""),
    NativeWord("general-vocabulary:noun:sala", "a sala", "гостиная", ""),
    NativeWord("general-vocabulary:noun:espelho", "o espelho", "зеркало", ""),
    NativeWord("general-vocabulary:noun:chave", "a chave", "ключ", ""),
    NativeWord("general-vocabulary:noun:teto", "o teto", "потолок", ""),
    NativeWord("general-vocabulary:noun:objeto", "o objeto", "предмет", ""),
    NativeWord("general-vocabulary:noun:emprego", "o emprego", "работа, должность", ""),
    NativeWord("general-vocabulary:noun:escritorio", "o escritório", "офис", ""),
    NativeWord("general-vocabulary:noun:empresa", "a empresa", "компания", ""),
    NativeWord("general-vocabulary:noun:reuniao", "a reunião", "собрание, встреча", ""),
    NativeWord("general-vocabulary:noun:salario", "o salário", "зарплата", ""),
    NativeWord("general-vocabulary:noun:cliente", "o/a cliente", "клиент", ""),
    NativeWord("general-vocabulary:noun:rua", "a rua", "улица", ""),
    NativeWord("general-vocabulary:noun:praca", "a praça", "площадь", ""),
    NativeWord("general-vocabulary:noun:avenida", "a avenida", "проспект", ""),
    NativeWord("general-vocabulary:noun:ponte", "a ponte", "мост", ""),
    NativeWord("general-vocabulary:noun:estacao", "a estação", "вокзал, станция", ""),
    NativeWord("general-vocabulary:noun:paragem", "a paragem", "остановка", ""),
    NativeWord("general-vocabulary:verb:cozer", "cozer", "варить", ""),
    NativeWord("general-vocabulary:verb:fritar", "fritar", "жарить", ""),
    NativeWord("general-vocabulary:verb:assar", "assar", "печь, жарить в духовке", ""),
    NativeWord("general-vocabulary:verb:cortar", "cortar", "резать", ""),
    NativeWord("general-vocabulary:verb:misturar", "misturar", "смешивать", ""),
    NativeWord("general-vocabulary:verb:provar", "provar", "пробовать на вкус", ""),
    NativeWord("general-vocabulary:verb:respirar", "respirar", "дышать", ""),
    NativeWord("general-vocabulary:verb:relaxar", "relaxar", "расслабляться", ""),
    NativeWord("general-vocabulary:verb:tossir", "tossir", "кашлять", ""),
    NativeWord("general-vocabulary:verb:espirrar", "espirrar", "чихать", ""),
    NativeWord("general-vocabulary:verb:curar", "curar", "лечить, вылечивать", ""),
    NativeWord("general-vocabulary:verb:sarar", "sarar", "заживать, выздоравливать", ""),
    NativeWord("general-vocabulary:adjective:feliz", "feliz", "счастливый", ""),
    NativeWord("general-vocabulary:adjective:ocupado", "ocupado / ocupada", "занятой", ""),
    NativeWord("general-vocabulary:adjective:livre", "livre", "свободный", ""),
    NativeWord("general-vocabulary:adjective:nervoso", "nervoso / nervosa", "нервный", ""),
    NativeWord("general-vocabulary:adjective:gentil", "gentil", "добрый, любезный", ""),
    NativeWord("general-vocabulary:adjective:educado", "educado / educada", "воспитанный", ""),
    NativeWord("general-vocabulary:verb:dizer", "dizer", "сказать, говорить", ""),
    NativeWord("general-vocabulary:verb:responder", "responder", "отвечать", ""),
    NativeWord("general-vocabulary:verb:explicar", "explicar", "объяснять", ""),
    NativeWord("general-vocabulary:verb:entender", "entender", "понимать", ""),
    NativeWord("general-vocabulary:verb:conversar", "conversar", "беседовать", ""),
    NativeWord("general-vocabulary:verb:contar", "contar", "рассказывать, считать", ""),
    NativeWord("general-vocabulary:verb:chegar", "chegar", "прибывать", ""),
    NativeWord("general-vocabulary:verb:voltar", "voltar", "возвращаться", ""),
    NativeWord("general-vocabulary:verb:subir", "subir", "подниматься", ""),
    NativeWord("general-vocabulary:verb:descer", "descer", "спускаться", ""),
    NativeWord("general-vocabulary:verb:caminhar", "caminhar", "идти пешком", ""),
    NativeWord("general-vocabulary:verb:viajar", "viajar", "путешествовать", "")
)

val nativeGeneralCards = listOf(
    NativeWord("general-vocabulary:verb:ter", "ter", "иметь", ""),
    NativeWord("general-vocabulary:verb:haver", "haver", "иметься, существовать", ""),
    NativeWord("general-vocabulary:verb:vir", "vir", "приходить", ""),
    NativeWord("general-vocabulary:verb:dizer", "dizer", "сказать, говорить", ""),
    NativeWord("general-vocabulary:verb:poder", "poder", "мочь", ""),
    NativeWord("general-vocabulary:verb:dever", "dever", "быть должным", ""),
    NativeWord("general-vocabulary:verb:ficar", "ficar", "оставаться, находиться", ""),
    NativeWord("general-vocabulary:verb:passar", "passar", "проходить, проводить (время)", ""),
    NativeWord("general-vocabulary:verb:chegar", "chegar", "прибывать", ""),
    NativeWord("general-vocabulary:verb:levar", "levar", "нести, уносить", ""),
    NativeWord("general-vocabulary:verb:trazer", "trazer", "приносить", ""),
    NativeWord("general-vocabulary:verb:deixar", "deixar", "оставлять, позволять", ""),
    NativeWord("general-vocabulary:verb:encontrar", "encontrar", "находить, встречать", ""),
    NativeWord("general-vocabulary:verb:pensar", "pensar", "думать", ""),
    NativeWord("general-vocabulary:verb:achar", "achar", "считать, находить", ""),
    NativeWord("general-vocabulary:verb:voltar", "voltar", "возвращаться", ""),
    NativeWord("general-vocabulary:verb:levantar-se", "levantar-se", "вставать", ""),
    NativeWord("general-vocabulary:verb:deitar-se", "deitar-se", "ложиться", ""),
    NativeWord("general-vocabulary:verb:acordar", "acordar", "просыпаться", ""),
    NativeWord("general-vocabulary:verb:vender", "vender", "продавать", ""),
    NativeWord("general-vocabulary:verb:pagar", "pagar", "платить", ""),
    NativeWord("general-vocabulary:verb:gastar", "gastar", "тратить", ""),
    NativeWord("general-vocabulary:verb:ensinar", "ensinar", "обучать", ""),
    NativeWord("general-vocabulary:verb:escutar", "escutar", "слушать", ""),
    NativeWord("general-vocabulary:verb:cantar", "cantar", "петь", ""),
    NativeWord("general-vocabulary:verb:dancar", "dançar", "танцевать", ""),
    NativeWord("general-vocabulary:verb:perder", "perder", "терять, проигрывать", ""),
    NativeWord("general-vocabulary:verb:precisar", "precisar", "нуждаться", ""),
    NativeWord("general-vocabulary:verb:amar", "amar", "любить", ""),
    NativeWord("general-vocabulary:verb:odiar", "odiar", "ненавидеть", ""),
    NativeWord("general-vocabulary:verb:sentir", "sentir", "чувствовать", ""),
    NativeWord("general-vocabulary:verb:morrer", "morrer", "умирать", ""),
    NativeWord("general-vocabulary:verb:mudar", "mudar", "менять(ся)", ""),
    NativeWord("general-vocabulary:verb:mover", "mover", "двигать", ""),
    NativeWord("general-vocabulary:verb:tocar", "tocar", "трогать, играть на инструменте", ""),
    NativeWord("general-vocabulary:verb:pegar", "pegar", "брать, хватать", ""),
    NativeWord("general-vocabulary:verb:segurar", "segurar", "держать", ""),
    NativeWord("general-vocabulary:verb:soltar", "soltar", "отпускать", ""),
    NativeWord("general-vocabulary:verb:lancar", "lançar", "бросать, запускать", ""),
    NativeWord("general-vocabulary:verb:subir", "subir", "подниматься", ""),
    NativeWord("general-vocabulary:verb:descer", "descer", "спускаться", ""),
    NativeWord("general-vocabulary:verb:viajar", "viajar", "путешествовать", ""),
    NativeWord("general-vocabulary:verb:conduzir", "conduzir", "водить машину", ""),
    NativeWord("general-vocabulary:verb:dirigir", "dirigir", "управлять, вести", ""),
    NativeWord("general-vocabulary:verb:caminhar", "caminhar", "идти пешком", ""),
    NativeWord("general-vocabulary:verb:procurar", "procurar", "искать", ""),
    NativeWord("general-vocabulary:verb:encontrar-se", "encontrar-se", "встречаться", ""),
    NativeWord("general-vocabulary:verb:conhecer", "conhecer", "быть знакомым, знать", ""),
    NativeWord("general-vocabulary:verb:reconhecer", "reconhecer", "узнавать, признавать", ""),
    NativeWord("general-vocabulary:verb:lembrar", "lembrar", "помнить", ""),
    NativeWord("general-vocabulary:verb:imaginar", "imaginar", "воображать", ""),
    NativeWord("general-vocabulary:verb:sonhar", "sonhar", "мечтать", ""),
    NativeWord("general-vocabulary:verb:decidir", "decidir", "решать", ""),
    NativeWord("general-vocabulary:verb:tentar", "tentar", "пытаться", ""),
    NativeWord("general-vocabulary:verb:conseguir", "conseguir", "суметь, добиться", ""),
    NativeWord("general-vocabulary:verb:tratar", "tratar", "обращаться, лечить", ""),
    NativeWord("general-vocabulary:verb:cuidar", "cuidar", "заботиться", ""),
    NativeWord("general-vocabulary:verb:proteger", "proteger", "защищать", ""),
    NativeWord("general-vocabulary:verb:salvar", "salvar", "спасать", ""),
    NativeWord("general-vocabulary:verb:matar", "matar", "убивать", ""),
    NativeWord("general-vocabulary:verb:lutar", "lutar", "бороться", ""),
    NativeWord("general-vocabulary:verb:vencer", "vencer", "побеждать", ""),
    NativeWord("general-vocabulary:verb:responder", "responder", "отвечать", ""),
    NativeWord("general-vocabulary:verb:explicar", "explicar", "объяснять", ""),
    NativeWord("general-vocabulary:verb:entender", "entender", "понимать", ""),
    NativeWord("general-vocabulary:verb:compreender", "compreender", "понимать", ""),
    NativeWord("general-vocabulary:verb:duvidar", "duvidar", "сомневаться", ""),
    NativeWord("general-vocabulary:verb:concordar", "concordar", "соглашаться", ""),
    NativeWord("general-vocabulary:verb:discordar", "discordar", "не соглашаться", ""),
    NativeWord("general-vocabulary:verb:discutir", "discutir", "обсуждать, спорить", ""),
    NativeWord("general-vocabulary:verb:conversar", "conversar", "беседовать", ""),
    NativeWord("general-vocabulary:verb:contar", "contar", "рассказывать, считать", ""),
    NativeWord("general-vocabulary:verb:esconder", "esconder", "прятать", ""),
    NativeWord("general-vocabulary:verb:guardar", "guardar", "хранить", ""),
    NativeWord("general-vocabulary:verb:manter", "manter", "сохранять, поддерживать", ""),
    NativeWord("general-vocabulary:verb:continuar", "continuar", "продолжать", ""),
    NativeWord("general-vocabulary:verb:iniciar", "iniciar", "начинать", ""),
    NativeWord("general-vocabulary:verb:destruir", "destruir", "разрушать", ""),
    NativeWord("general-vocabulary:verb:quebrar", "quebrar", "ломать", ""),
    NativeWord("general-vocabulary:verb:reparar", "reparar", "чинить, замечать", ""),
    NativeWord("general-vocabulary:verb:secar", "secar", "сушить", ""),
    NativeWord("general-vocabulary:verb:cozer", "cozer", "варить", ""),
    NativeWord("general-vocabulary:verb:fritar", "fritar", "жарить", ""),
    NativeWord("general-vocabulary:verb:assar", "assar", "печь, жарить в духовке", ""),
    NativeWord("general-vocabulary:verb:cortar", "cortar", "резать", ""),
    NativeWord("general-vocabulary:verb:misturar", "misturar", "смешивать", ""),
    NativeWord("general-vocabulary:verb:juntar", "juntar", "соединять, собирать", ""),
    NativeWord("general-vocabulary:verb:separar", "separar", "разделять", ""),
    NativeWord("general-vocabulary:verb:dividir", "dividir", "делить", ""),
    NativeWord("general-vocabulary:verb:abracar", "abraçar", "обнимать", ""),
    NativeWord("general-vocabulary:verb:beijar", "beijar", "целовать", ""),
    NativeWord("general-vocabulary:verb:sorrir", "sorrir", "улыбаться", ""),
    NativeWord("general-vocabulary:verb:rir", "rir", "смеяться", ""),
    NativeWord("general-vocabulary:verb:sussurrar", "sussurrar", "шептать", ""),
    NativeWord("general-vocabulary:verb:calar-se", "calar-se", "замолчать", ""),
    NativeWord("general-vocabulary:verb:respirar", "respirar", "дышать", ""),
    NativeWord("general-vocabulary:verb:relaxar", "relaxar", "расслабляться", ""),
    NativeWord("general-vocabulary:verb:cansar-se", "cansar-se", "уставать", ""),
    NativeWord("general-vocabulary:verb:acontecer", "acontecer", "происходить, случаться", ""),
    NativeWord("general-vocabulary:verb:permitir", "permitir", "разрешать", ""),
    NativeWord("general-vocabulary:verb:proibir", "proibir", "запрещать", ""),
    NativeWord("general-vocabulary:verb:impedir", "impedir", "препятствовать", ""),
    NativeWord("general-vocabulary:verb:evitar", "evitar", "избегать", ""),
    NativeWord("general-vocabulary:verb:arriscar", "arriscar", "рисковать", ""),
    NativeWord("general-vocabulary:verb:organizar", "organizar", "организовывать", ""),
    NativeWord("general-vocabulary:verb:vestir", "vestir", "одевать", ""),
    NativeWord("general-vocabulary:verb:despir", "despir", "раздевать", ""),
    NativeWord("general-vocabulary:verb:calcar", "calçar", "обувать", ""),
    NativeWord("general-vocabulary:verb:pentear", "pentear", "расчёсывать", ""),
    NativeWord("general-vocabulary:verb:filmar", "filmar", "снимать видео", ""),
    NativeWord("general-vocabulary:verb:gravar", "gravar", "записывать", ""),
    NativeWord("general-vocabulary:verb:imprimir", "imprimir", "печатать", ""),
    NativeWord("general-vocabulary:verb:enviar", "enviar", "отправлять", ""),
    NativeWord("general-vocabulary:verb:entregar", "entregar", "доставлять, вручать", ""),
    NativeWord("general-vocabulary:verb:devolver", "devolver", "возвращать вещь", ""),
    NativeWord("general-vocabulary:verb:emprestar", "emprestar", "одалживать", ""),
    NativeWord("general-vocabulary:verb:pedir", "pedir", "просить, заказывать", ""),
    NativeWord("general-vocabulary:verb:oferecer", "oferecer", "предлагать, дарить", ""),
    NativeWord("general-vocabulary:verb:convidar", "convidar", "приглашать", ""),
    NativeWord("general-vocabulary:verb:visitar", "visitar", "посещать", ""),
    NativeWord("general-vocabulary:verb:mudar-se", "mudar-se", "переезжать", ""),
    NativeWord("general-vocabulary:verb:alugar", "alugar", "арендовать", ""),
    NativeWord("general-vocabulary:verb:reservar", "reservar", "бронировать", ""),
    NativeWord("general-vocabulary:verb:marcar", "marcar", "назначать встречу", ""),
    NativeWord("general-vocabulary:verb:atrasar-se", "atrasar-se", "опаздывать", ""),
    NativeWord("general-vocabulary:verb:apressar-se", "apressar-se", "торопиться", ""),
    NativeWord("general-vocabulary:verb:demorar", "demorar", "задерживаться, занимать время", ""),
    NativeWord("general-vocabulary:verb:durar", "durar", "длиться", ""),
    NativeWord("general-vocabulary:verb:funcionar", "funcionar", "функционировать, работать (о механизме)", ""),
    NativeWord("general-vocabulary:verb:ligar", "ligar", "включать, звонить", ""),
    NativeWord("general-vocabulary:verb:desligar", "desligar", "выключать", ""),
    NativeWord("general-vocabulary:verb:apagar", "apagar", "гасить, стирать", ""),
    NativeWord("general-vocabulary:verb:acender", "acender", "зажигать", ""),
    NativeWord("general-vocabulary:verb:carregar", "carregar", "заряжать, нести", ""),
    NativeWord("general-vocabulary:verb:descarregar", "descarregar", "разряжать, разгружать", ""),
    NativeWord("general-vocabulary:verb:instalar", "instalar", "устанавливать", ""),
    NativeWord("general-vocabulary:verb:utilizar", "utilizar", "использовать", ""),
    NativeWord("general-vocabulary:verb:usar", "usar", "использовать, носить", ""),
    NativeWord("general-vocabulary:verb:aproveitar", "aproveitar", "пользоваться, наслаждаться", ""),
    NativeWord("general-vocabulary:verb:poupar", "poupar", "экономить", ""),
    NativeWord("general-vocabulary:verb:investir", "investir", "инвестировать", ""),
    NativeWord("general-vocabulary:verb:custar", "custar", "стоить", ""),
    NativeWord("general-vocabulary:verb:valer", "valer", "иметь ценность", ""),
    NativeWord("general-vocabulary:verb:aumentar", "aumentar", "увеличивать", ""),
    NativeWord("general-vocabulary:verb:diminuir", "diminuir", "уменьшать", ""),
    NativeWord("general-vocabulary:verb:reduzir", "reduzir", "сокращать", ""),
    NativeWord("general-vocabulary:verb:melhorar", "melhorar", "улучшать", ""),
    NativeWord("general-vocabulary:verb:piorar", "piorar", "ухудшать", ""),
    NativeWord("general-vocabulary:verb:transformar", "transformar", "превращать", ""),
    NativeWord("general-vocabulary:verb:tornar-se", "tornar-se", "становиться", ""),
    NativeWord("general-vocabulary:verb:acreditar", "acreditar", "верить", ""),
    NativeWord("general-vocabulary:verb:confiar", "confiar", "доверять", ""),
    NativeWord("general-vocabulary:verb:desconfiar", "desconfiar", "не доверять", ""),
    NativeWord("general-vocabulary:verb:suspeitar", "suspeitar", "подозревать", ""),
    NativeWord("general-vocabulary:verb:influenciar", "influenciar", "влиять", ""),
    NativeWord("general-vocabulary:verb:convencer", "convencer", "убеждать", ""),
    NativeWord("general-vocabulary:verb:persuadir", "persuadir", "уговаривать", ""),
    NativeWord("general-vocabulary:verb:recusar", "recusar", "отказывать(ся)", ""),
    NativeWord("general-vocabulary:verb:aceitar", "aceitar", "принимать, соглашаться", ""),
    NativeWord("general-vocabulary:verb:rejeitar", "rejeitar", "отвергать", ""),
    NativeWord("general-vocabulary:verb:admitir", "admitir", "допускать, признавать", ""),
    NativeWord("general-vocabulary:verb:negar", "negar", "отрицать", ""),
    NativeWord("general-vocabulary:verb:confirmar", "confirmar", "подтверждать", ""),
    NativeWord("general-vocabulary:verb:garantir", "garantir", "гарантировать", ""),
    NativeWord("general-vocabulary:verb:prometer", "prometer", "обещать", ""),
    NativeWord("general-vocabulary:verb:jurar", "jurar", "клясться", ""),
    NativeWord("general-vocabulary:verb:mentir", "mentir", "лгать", ""),
    NativeWord("general-vocabulary:verb:enganar", "enganar", "обманывать", ""),
    NativeWord("general-vocabulary:verb:trair", "trair", "предавать", ""),
    NativeWord("general-vocabulary:verb:perdoar", "perdoar", "прощать", ""),
    NativeWord("general-vocabulary:verb:agradecer", "agradecer", "благодарить", ""),
    NativeWord("general-vocabulary:verb:desculpar-se", "desculpar-se", "извиняться", ""),
    NativeWord("general-vocabulary:verb:cumprimentar", "cumprimentar", "приветствовать", ""),
    NativeWord("general-vocabulary:verb:despedir-se", "despedir-se", "прощаться", ""),
    NativeWord("general-vocabulary:verb:apresentar", "apresentar", "представлять (кого-то)", ""),
    NativeWord("general-vocabulary:verb:casar-se", "casar-se", "жениться, выходить замуж", ""),
    NativeWord("general-vocabulary:verb:divorciar-se", "divorciar-se", "разводиться", ""),
    NativeWord("general-vocabulary:verb:namorar", "namorar", "встречаться (романтически)", ""),
    NativeWord("general-vocabulary:verb:apaixonar-se", "apaixonar-se", "влюбляться", ""),
    NativeWord("general-vocabulary:verb:engravidar", "engravidar", "забеременеть", ""),
    NativeWord("general-vocabulary:verb:criar", "criar", "создавать, растить", ""),
    NativeWord("general-vocabulary:verb:educar", "educar", "воспитывать", ""),
    NativeWord("general-vocabulary:verb:obedecer", "obedecer", "подчиняться", ""),
    NativeWord("general-vocabulary:verb:desobedecer", "desobedecer", "не подчиняться", ""),
    NativeWord("general-vocabulary:verb:respeitar", "respeitar", "уважать", ""),
    NativeWord("general-vocabulary:verb:admirar", "admirar", "восхищаться", ""),
    NativeWord("general-vocabulary:verb:invejar", "invejar", "завидовать", ""),
    NativeWord("general-vocabulary:verb:cheirar", "cheirar", "пахнуть, нюхать", ""),
    NativeWord("general-vocabulary:verb:provar", "provar", "пробовать на вкус", ""),
    NativeWord("general-vocabulary:verb:saborear", "saborear", "смаковать", ""),
    NativeWord("general-vocabulary:verb:engolir", "engolir", "глотать", ""),
    NativeWord("general-vocabulary:verb:mastigar", "mastigar", "жевать", ""),
    NativeWord("general-vocabulary:verb:adoecer", "adoecer", "заболеть", ""),
    NativeWord("general-vocabulary:verb:curar", "curar", "лечить, вылечивать", ""),
    NativeWord("general-vocabulary:verb:sarar", "sarar", "заживать, выздоравливать", ""),
    NativeWord("general-vocabulary:verb:tossir", "tossir", "кашлять", ""),
    NativeWord("general-vocabulary:verb:espirrar", "espirrar", "чихать", ""),
    NativeWord("general-vocabulary:verb:sangrar", "sangrar", "кровоточить", ""),
    NativeWord("general-vocabulary:verb:magoar-se", "magoar-se", "ушибиться, обидеться", ""),
    NativeWord("general-vocabulary:verb:ferir", "ferir", "ранить", ""),
    NativeWord("general-vocabulary:verb:tremer", "tremer", "дрожать", ""),
    NativeWord("general-vocabulary:verb:suar", "suar", "потеть", ""),
    NativeWord("general-vocabulary:verb:acabar-de", "acabar de", "только что сделать", ""),
    NativeWord("general-vocabulary:verb:deixar-de", "deixar de", "перестать делать", ""),
    NativeWord("general-vocabulary:verb:comecar-a", "começar a", "начинать делать", ""),
    NativeWord("general-vocabulary:verb:acostumar-se", "acostumar-se", "привыкать", ""),
    NativeWord("general-vocabulary:verb:habituar-se", "habituar-se", "привыкать", ""),
    NativeWord("general-vocabulary:noun:apartamento", "o apartamento — os apartamentos", "квартира", ""),
    NativeWord("general-vocabulary:noun:sala", "a sala — as salas", "гостиная", ""),
    NativeWord("general-vocabulary:noun:espelho", "o espelho — os espelhos", "зеркало", ""),
    NativeWord("general-vocabulary:noun:chao", "chão", "пол", ""),
    NativeWord("general-vocabulary:noun:teto", "o teto — os tetos", "потолок", ""),
    NativeWord("general-vocabulary:noun:chave", "a chave — as chaves", "ключ", ""),
    NativeWord("general-vocabulary:noun:mensagem", "mensagem", "сообщение", ""),
    NativeWord("general-vocabulary:noun:revista", "revista", "журнал", ""),
    NativeWord("general-vocabulary:noun:conta", "conta", "счёт", ""),
    NativeWord("general-vocabulary:noun:emprego", "o emprego — os empregos", "работа, должность", ""),
    NativeWord("general-vocabulary:noun:escritorio", "o escritório — os escritórios", "офис", ""),
    NativeWord("general-vocabulary:noun:empresa", "a empresa — as empresas", "компания", ""),
    NativeWord("general-vocabulary:noun:reuniao", "a reunião — as reuniões", "собрание, встреча", ""),
    NativeWord("general-vocabulary:noun:salario", "o salário — os salários", "зарплата", ""),
    NativeWord("general-vocabulary:noun:cliente", "o/a cliente — os/as clientes", "клиент", ""),
    NativeWord("general-vocabulary:noun:negocio", "negócio", "дело, бизнес", ""),
    NativeWord("general-vocabulary:noun:loja", "loja", "магазин", ""),
    NativeWord("general-vocabulary:noun:preco", "preço", "цена", ""),
    NativeWord("general-vocabulary:noun:desconto", "desconto", "скидка", ""),
    NativeWord("general-vocabulary:noun:camisa", "camisa", "рубашка", ""),
    NativeWord("general-vocabulary:noun:jantar", "jantar", "ужин", ""),
    NativeWord("general-vocabulary:noun:arroz", "arroz", "рис", ""),
    NativeWord("general-vocabulary:noun:legume", "legume", "овощ", ""),
    NativeWord("general-vocabulary:noun:vinho", "vinho", "вино", ""),
    NativeWord("general-vocabulary:noun:azeite", "azeite", "оливковое масло", ""),
    NativeWord("general-vocabulary:noun:rua", "a rua — as ruas", "улица", ""),
    NativeWord("general-vocabulary:noun:aldeia", "aldeia", "деревня", ""),
    NativeWord("general-vocabulary:noun:praca", "a praça — as praças", "площадь", ""),
    NativeWord("general-vocabulary:noun:avenida", "a avenida — as avenidas", "проспект", ""),
    NativeWord("general-vocabulary:noun:ponte", "a ponte — as pontes", "мост", ""),
    NativeWord("general-vocabulary:noun:estrada", "estrada", "дорога, шоссе", ""),
    NativeWord("general-vocabulary:noun:barco", "barco", "лодка, корабль", ""),
    NativeWord("general-vocabulary:noun:viagem", "viagem", "путешествие", ""),
    NativeWord("general-vocabulary:noun:estacao", "a estação — as estações", "вокзал, станция", ""),
    NativeWord("general-vocabulary:noun:paragem", "a paragem — as paragens", "остановка", ""),
    NativeWord("general-vocabulary:noun:doente", "doente", "больной", ""),
    NativeWord("general-vocabulary:noun:doenca", "doença", "болезнь", ""),
    NativeWord("general-vocabulary:noun:remedio", "remédio", "лекарство", ""),
    NativeWord("general-vocabulary:noun:dor", "dor", "боль", ""),
    NativeWord("general-vocabulary:noun:saude", "saúde", "здоровье", ""),
    NativeWord("general-vocabulary:noun:exame", "exame", "экзамен", ""),
    NativeWord("general-vocabulary:noun:licao", "lição", "урок (тема)", ""),
    NativeWord("general-vocabulary:noun:marido", "marido", "муж", ""),
    NativeWord("general-vocabulary:noun:esposa", "esposa", "жена", ""),
    NativeWord("general-vocabulary:noun:pessoa", "pessoa", "человек", ""),
    NativeWord("general-vocabulary:noun:gente", "gente", "люди", ""),
    NativeWord("general-vocabulary:noun:coracao", "coração", "сердце", ""),
    NativeWord("general-vocabulary:noun:corpo", "corpo", "тело", ""),
    NativeWord("general-vocabulary:noun:objeto", "o objeto — os objetos", "предмет", ""),
    NativeWord("general-vocabulary:noun:solucao", "solução", "решение", ""),
    NativeWord("general-vocabulary:noun:pergunta", "pergunta", "вопрос", ""),
    NativeWord("general-vocabulary:noun:resposta", "resposta", "ответ", ""),
    NativeWord("general-vocabulary:noun:noticia", "notícia", "новость", ""),
    NativeWord("general-vocabulary:noun:verdade", "verdade", "правда", ""),
    NativeWord("general-vocabulary:noun:mentira", "mentira", "ложь", ""),
    NativeWord("general-vocabulary:noun:motivo", "motivo", "причина", ""),
    NativeWord("general-vocabulary:noun:razao", "razão", "причина, правота", ""),
    NativeWord("general-vocabulary:noun:exemplo", "exemplo", "пример", ""),
    NativeWord("general-vocabulary:noun:momento", "momento", "момент", ""),
    NativeWord("general-vocabulary:noun:morte", "morte", "смерть", ""),
    NativeWord("general-vocabulary:noun:sonho", "sonho", "мечта, сон", ""),
    NativeWord("general-vocabulary:noun:medo", "medo", "страх", ""),
    NativeWord("general-vocabulary:noun:alegria", "alegria", "радость", ""),
    NativeWord("general-vocabulary:noun:tristeza", "tristeza", "грусть", ""),
    NativeWord("general-vocabulary:noun:raiva", "raiva", "злость", ""),
    NativeWord("general-vocabulary:noun:surpresa", "surpresa", "удивление", ""),
    NativeWord("general-vocabulary:noun:felicidade", "felicidade", "счастье", ""),
    NativeWord("general-vocabulary:noun:amor", "amor", "любовь", ""),
    NativeWord("general-vocabulary:noun:odio", "ódio", "ненависть", ""),
    NativeWord("general-vocabulary:noun:esperanca", "esperança", "надежда", ""),
    NativeWord("general-vocabulary:noun:sorte", "sorte", "удача", ""),
    NativeWord("general-vocabulary:noun:azar", "azar", "невезение", ""),
    NativeWord("general-vocabulary:noun:arte", "arte", "искусство", ""),
    NativeWord("general-vocabulary:noun:cultura", "cultura", "культура", ""),
    NativeWord("general-vocabulary:noun:natureza", "natureza", "природа", ""),
    NativeWord("general-vocabulary:noun:montanha", "montanha", "гора", ""),
    NativeWord("general-vocabulary:noun:ar", "ar", "воздух", ""),
    NativeWord("general-vocabulary:noun:gente-jovem", "gente jovem", "молодёжь", ""),
    NativeWord("general-vocabulary:noun:vizinhanca", "vizinhança", "соседство", ""),
    NativeWord("general-vocabulary:noun:bairro", "bairro", "квартал, район", ""),
    NativeWord("general-vocabulary:noun:espaco", "espaço", "пространство", ""),
    NativeWord("general-vocabulary:noun:mundo", "mundo", "мир", ""),
    NativeWord("general-vocabulary:noun:pais", "país", "страна", ""),
    NativeWord("general-vocabulary:noun:governo", "governo", "правительство", ""),
    NativeWord("general-vocabulary:noun:lei", "lei", "закон", ""),
    NativeWord("general-vocabulary:noun:guerra", "guerra", "война", ""),
    NativeWord("general-vocabulary:noun:paz", "paz", "мир (отсутствие войны)", ""),
    NativeWord("general-vocabulary:noun:sociedade", "sociedade", "общество", ""),
    NativeWord("general-vocabulary:noun:economia", "economia", "экономика", ""),
    NativeWord("general-vocabulary:noun:opiniao", "opinião", "мнение", ""),
    NativeWord("general-vocabulary:noun:decisao", "decisão", "решение", ""),
    NativeWord("general-vocabulary:noun:conselho", "conselho", "совет", ""),
    NativeWord("general-vocabulary:noun:apoio", "apoio", "поддержка", ""),
    NativeWord("general-vocabulary:adjective:jovem", "jovem", "молодой", ""),
    NativeWord("general-vocabulary:adjective:feliz", "feliz", "счастливый", ""),
    NativeWord("general-vocabulary:adjective:ocupado", "ocupado / ocupada", "занятой", ""),
    NativeWord("general-vocabulary:adjective:livre", "livre", "свободный", ""),
    NativeWord("general-vocabulary:adjective:importante", "importante", "важный", ""),
    NativeWord("general-vocabulary:adjective:interessante", "interessante", "интересный", ""),
    NativeWord("general-vocabulary:adjective:chato", "chato", "скучный, надоедливый", ""),
    NativeWord("general-vocabulary:adjective:engracado", "engraçado", "смешной", ""),
    NativeWord("general-vocabulary:adjective:serio", "sério", "серьёзный", ""),
    NativeWord("general-vocabulary:adjective:nervoso", "nervoso / nervosa", "нервный", ""),
    NativeWord("general-vocabulary:adjective:barato", "barato", "дешёвый", ""),
    NativeWord("general-vocabulary:adjective:limpo", "limpo", "чистый", ""),
    NativeWord("general-vocabulary:adjective:sujo", "sujo", "грязный", ""),
    NativeWord("general-vocabulary:adjective:cheio", "cheio", "полный", ""),
    NativeWord("general-vocabulary:adjective:vazio", "vazio", "пустой", ""),
    NativeWord("general-vocabulary:adjective:seco", "seco", "сухой", ""),
    NativeWord("general-vocabulary:adjective:molhado", "molhado", "мокрый", ""),
    NativeWord("general-vocabulary:adjective:salgado", "salgado", "солёный", ""),
    NativeWord("general-vocabulary:adjective:amargo", "amargo", "горький", ""),
    NativeWord("general-vocabulary:adjective:azedo", "azedo", "кислый", ""),
    NativeWord("general-vocabulary:adjective:macio", "macio", "мягкий", ""),
    NativeWord("general-vocabulary:adjective:duro", "duro", "твёрдый", ""),
    NativeWord("general-vocabulary:adjective:pesado", "pesado", "тяжёлый", ""),
    NativeWord("general-vocabulary:adjective:leve", "leve", "лёгкий по весу", ""),
    NativeWord("general-vocabulary:adjective:largo", "largo", "широкий", ""),
    NativeWord("general-vocabulary:adjective:estreito", "estreito", "узкий", ""),
    NativeWord("general-vocabulary:adjective:saudavel", "saudável", "здоровый", ""),
    NativeWord("general-vocabulary:adjective:inteligente", "inteligente", "умный", ""),
    NativeWord("general-vocabulary:adjective:estupido", "estúpido", "глупый", ""),
    NativeWord("general-vocabulary:adjective:gentil", "gentil", "добрый, любезный", ""),
    NativeWord("general-vocabulary:adjective:educado", "educado / educada", "воспитанный", ""),
    NativeWord("general-vocabulary:adjective:antipatico", "antipático", "неприятный", ""),
    NativeWord("general-vocabulary:adjective:honesto", "honesto", "честный", ""),
    NativeWord("general-vocabulary:adjective:diferente", "diferente", "другой, отличный", ""),
    NativeWord("general-vocabulary:adjective:igual", "igual", "одинаковый", ""),
    NativeWord("general-vocabulary:adjective:mesmo", "mesmo", "тот же самый", ""),
    NativeWord("general-vocabulary:adjective:proprio", "próprio", "собственный", ""),
    NativeWord("general-vocabulary:adjective:pronto", "pronto", "готовый", ""),
    NativeWord("general-vocabulary:adjective:seguro", "seguro", "безопасный, уверенный", ""),
    NativeWord("general-vocabulary:adjective:perigoso", "perigoso", "опасный", ""),
    NativeWord("general-vocabulary:adverb-or-other:fora", "fora", "снаружи", ""),
    NativeWord("general-vocabulary:adverb-or-other:muito", "muito", "очень, много", ""),
    NativeWord("general-vocabulary:adverb-or-other:pouco", "pouco", "мало", ""),
    NativeWord("general-vocabulary:adverb-or-other:bem", "bem", "хорошо", ""),
    NativeWord("general-vocabulary:adverb-or-other:mal", "mal", "плохо", ""),
    NativeWord("general-vocabulary:adverb-or-other:talvez", "talvez", "возможно", ""),
    NativeWord("general-vocabulary:adverb-or-other:tambem", "também", "тоже", ""),
    NativeWord("general-vocabulary:adverb-or-other:ainda", "ainda", "ещё", ""),
    NativeWord("general-vocabulary:adverb-or-other:outra-vez", "outra vez", "снова", ""),
    NativeWord("general-vocabulary:adverb-or-other:rapidamente", "rapidamente", "быстро", ""),
    NativeWord("general-vocabulary:adverb-or-other:devagar", "devagar", "медленно", "")
)

val nativeSchoolCards = listOf(
    NativeWord("v0083", "ler", "читать", "Lê o texto."),
    NativeWord("v0062", "escrever", "писать", "Escreve no caderno."),
    NativeWord("v0242", "completar", "дополнять", "Completa a frase."),
    NativeWord("v0258", "ligar", "соединять", "Liga as palavras."),
    NativeWord("v0682", "assinalar", "отмечать", "Assinala a resposta certa."),
    NativeWord("v0379", "pintar", "раскрашивать", "Pinta o desenho."),
    NativeWord("v0154", "escolher", "выбирать", "Escolhe uma opção."),
    NativeWord("v0091", "responder", "отвечать", "Responde à pergunta.")
)

val nativeTopics = listOf(
    NativeTopic("topic:vocabulary-scenes", "Мир в картинках", listOf(NativeSet("collection:scene-set-street", "На нашей улице", listOf("scene-word:a-casa", "scene-word:a-escola", "scene-word:a-loja", "scene-word:a-farmacia", "scene-word:o-cafe", "scene-word:a-rua", "scene-word:o-autocarro", "scene-word:a-paragem")), NativeSet("collection:scene-set-beach", "На пляже", listOf("scene-word:o-barco", "scene-word:o-mar", "scene-word:o-guarda-sol", "scene-word:a-areia", "scene-word:o-balde", "scene-word:a-toalha")), NativeSet("collection:scene-set-garden", "В саду", listOf("scene-word:a-arvore", "scene-word:a-borboleta", "scene-word:a-abelha", "scene-word:a-flor", "scene-word:o-caracol", "scene-word:a-folha", "scene-word:a-relva")), NativeSet("collection:scene-set-rain", "Под дождём", listOf("scene-word:a-nuvem", "scene-word:a-chuva", "scene-word:o-vento", "scene-word:o-guarda-chuva", "scene-word:o-casaco", "scene-word:as-botas", "scene-word:a-poca")), NativeSet("collection:scene-set-weather", "После дождя", listOf("scene-word:a-nuvem", "scene-word:o-vento", "scene-word:a-chuva", "scene-word:o-guarda-chuva", "scene-word:o-casaco", "scene-word:as-botas", "scene-word:a-poca")), NativeSet("collection:scene-set-farm", "На ферме", listOf("scene-word:a-vaca", "scene-word:o-cavalo", "scene-word:o-gato", "scene-word:o-porco", "scene-word:a-ovelha", "scene-word:a-galinha", "scene-word:o-pato")), NativeSet("collection:scene-set-market", "На рынке", listOf("scene-word:a-maca", "scene-word:a-banana", "scene-word:a-laranja", "scene-word:a-cesta", "scene-word:o-tomate", "scene-word:a-batata", "scene-word:a-cenoura")), NativeSet("collection:scene-set-school", "Собираемся в школу", listOf("scene-word:a-mochila", "scene-word:o-caderno", "scene-word:o-lapis", "scene-word:a-caneta", "scene-word:o-livro", "scene-word:a-borracha", "scene-word:a-regua")), NativeSet("collection:scene-set-breakfast", "За завтраком", listOf("scene-word:a-cadeira", "scene-word:o-leite", "scene-word:o-pao", "scene-word:a-mesa", "scene-word:o-prato", "scene-word:a-chavena", "scene-word:a-colher", "scene-word:o-ovo")), NativeSet("collection:scene-set-park", "В парке", listOf("scene-word:o-parque", "scene-word:o-passaro", "scene-word:a-arvore", "scene-word:o-banco", "scene-word:a-bicicleta", "scene-word:o-cao", "scene-word:a-bola")))),
    NativeTopic("topic:vocabulary-clothing", "Одежда", listOf(NativeSet("collection:clothing-basics", "Одежда и обувь", listOf("clothing-camisola", "clothing-casaco", "clothing-cachecol", "clothing-calcas", "clothing-calcoes", "clothing-saia", "clothing-pijama", "clothing-blusa", "clothing-vestido", "clothing-sapatos")))),
    NativeTopic("topic:vocabulary-lessons", "Из уроков", listOf(NativeSet("collection:pairs-introductions", "Знакомство", listOf("study:chunk:ola", "study:chunk:como-te-chamas", "study:chunk:chamo-me", "study:chunk:sou-name", "study:chunk:muito-prazer")), NativeSet("collection:pairs-familiar-objects", "Знакомые предметы", listOf("study:noun:mesa", "study:noun:caixa", "study:noun:porta", "study:noun:janela", "study:noun:gato", "study:noun:chave", "study:noun:livro", "study:noun:sala", "study:noun:cadeira", "study:noun:cama", "study:noun:quarto", "study:noun:armario", "study:noun:copo")), NativeSet("collection:pairs-location", "Где находится?", listOf("study:chunk:onde-esta", "study:chunk:dentro-de", "study:chunk:em-cima-de", "study:chunk:debaixo-de", "study:chunk:ao-lado-de")), NativeSet("collection:pairs-being-having", "Быть, иметь, есть", listOf("study:verb:ser:identity", "study:verb:estar:state", "study:verb:ter:possession", "study:chunk:ha-presence")), NativeSet("collection:pairs-city", "Места в городе", listOf("study:noun:estacao", "study:noun:hotel", "study:noun:farmacia", "study:noun:centro", "study:chunk:onde-fica", "study:verb:ficar:location")))),
    NativeTopic("topic:vocabulary-house", "Дом", listOf(NativeSet("collection:home-rooms", "Комнаты и части дома", listOf("house-telhado", "house-chamine", "house-janela", "house-varanda", "house-quarto", "house-casa-de-banho", "house-sala", "house-cozinha", "house-escritorio", "house-escada", "house-corrimao", "house-hall-de-entrada", "house-res-do-chao", "house-primeiro-andar", "house-sotao", "house-cave", "house-garagem", "house-teto", "house-lareira")), NativeSet("collection:home-furniture", "Мебель и техника", listOf("house-cortina", "house-persiana", "house-mesa-de-cabeceira", "house-guarda-fatos", "house-cama", "house-tapete", "house-secretaria", "house-cadeiras", "house-mesa", "house-sofa", "house-televisao", "house-aparelhagem", "house-comoda", "house-estante-de-livros")), NativeSet("collection:kitchen-bath", "Посуда и ванная", listOf("house-tacho", "house-talheres", "house-chuveiro", "house-lava-louca", "house-sanita", "house-toalha", "house-espelho", "house-prato", "house-banheira")), NativeSet("collection:garden-transport", "Сад и транспорт", listOf("house-grelhador", "house-relva", "house-guarda-sol", "house-jardim", "house-mesa-de-jardim", "house-carro", "house-bicicleta", "house-caixa-de-ferramentas", "house-trotinete")), NativeSet("collection:house-room-set-jardim", "Сад", listOf("house-grelhador", "house-relva", "house-mesa-de-jardim", "house-guarda-sol")), NativeSet("collection:house-room-set-quarto", "Спальня", listOf("house-mesa-de-cabeceira", "house-guarda-fatos", "house-cama", "house-tapete", "house-secretaria", "house-comoda")), NativeSet("collection:house-room-set-cozinha", "Кухня", listOf("house-talheres", "house-lava-louca", "house-cadeiras", "house-mesa", "house-tacho", "house-prato")), NativeSet("collection:house-room-set-sala", "Гостиная", listOf("house-sofa", "house-televisao", "house-aparelhagem", "house-estante-de-livros", "house-tapete")), NativeSet("collection:house-room-set-garagem", "Гараж", listOf("house-carro", "house-bicicleta", "house-caixa-de-ferramentas", "house-trotinete")), NativeSet("collection:house-room-set-casa-de-banho", "Ванная комната", listOf("house-toalha", "house-espelho", "house-banheira", "house-sanita", "house-chuveiro")), NativeSet("collection:vocabulary-lesson:home", "Дом и вещи", listOf("general-vocabulary:noun:apartamento", "general-vocabulary:noun:chave", "general-vocabulary:noun:objeto")))),
    NativeTopic("topic:vocabulary-verbs", "Глаголы на каждый день", listOf(NativeSet("collection:pairs-verbs-movement", "Движение и поездки", listOf("v0006", "v0016", "v0017", "v0029", "v0035", "v0030", "v0047", "v0075", "v0114", "v0157", "v0297", "v0021", "v0067", "v0102")), NativeSet("collection:pairs-verbs-communication", "Общение", listOf("v0018", "v0085", "v0091", "v0042", "v0062", "v0083", "v0094", "v0036")), NativeSet("collection:pairs-verbs-study-work", "Работа и учёба", listOf("v0048", "v0099", "v0340", "v0024", "v0011", "v0081", "v0066", "v0142")), NativeSet("collection:pairs-verbs-everyday-actions", "Повседневные действия", listOf("v0068", "v0020", "v0154", "v0135", "v0058", "v0061", "v0106", "v0005")), NativeSet("collection:pairs-verbs-food-shopping", "Еда и покупки", listOf("v0123", "v0270", "v0218", "v0126", "v0124", "v0079", "v0050")), NativeSet("collection:pairs-verbs-rest", "Отдых и свободное время", listOf("v0158", "v0294", "v0522", "v0432", "v0960", "v0523", "v0196", "v0153")), NativeSet("collection:pairs-verbs-feelings", "Желания и чувства", listOf("v0057", "v0012", "v0034")), NativeSet("collection:vocabulary-lesson:communication", "Разговор и понимание", listOf("general-vocabulary:verb:dizer", "general-vocabulary:verb:conversar", "general-vocabulary:verb:contar")), NativeSet("collection:vocabulary-lesson:movement", "Движение и поездки", listOf("general-vocabulary:verb:caminhar")))),
    NativeTopic("topic:everyday", "Повседневная жизнь", listOf(NativeSet("collection:scene-set-school", "Собираемся в школу", listOf("scene-word:a-mochila", "scene-word:o-caderno", "scene-word:o-lapis", "scene-word:a-caneta", "scene-word:o-livro", "scene-word:a-borracha", "scene-word:a-regua")), NativeSet("collection:scene-set-breakfast", "За завтраком", listOf("scene-word:a-cadeira", "scene-word:o-leite", "scene-word:o-pao", "scene-word:a-mesa", "scene-word:o-prato", "scene-word:a-chavena", "scene-word:a-colher", "scene-word:o-ovo")))),
    NativeTopic("topic:food", "Еда и покупки", listOf(NativeSet("collection:scene-set-market", "На рынке", listOf("scene-word:a-maca", "scene-word:a-banana", "scene-word:a-laranja", "scene-word:a-cesta", "scene-word:o-tomate", "scene-word:a-batata", "scene-word:a-cenoura")), NativeSet("collection:scene-set-breakfast", "За завтраком", listOf("scene-word:a-cadeira", "scene-word:o-leite", "scene-word:o-pao", "scene-word:a-mesa", "scene-word:o-prato", "scene-word:a-chavena", "scene-word:a-colher", "scene-word:o-ovo")), NativeSet("collection:vocabulary-lesson:cooking", "Готовим еду", listOf("general-vocabulary:verb:cozer", "general-vocabulary:verb:fritar", "general-vocabulary:verb:assar", "general-vocabulary:verb:cortar", "general-vocabulary:verb:misturar", "general-vocabulary:verb:provar")))),
    NativeTopic("topic:nature", "Природа", listOf(NativeSet("collection:scene-set-beach", "На пляже", listOf("scene-word:o-barco", "scene-word:o-mar", "scene-word:o-guarda-sol", "scene-word:a-areia", "scene-word:o-balde", "scene-word:a-toalha")), NativeSet("collection:scene-set-garden", "В саду", listOf("scene-word:a-arvore", "scene-word:a-borboleta", "scene-word:a-abelha", "scene-word:a-flor", "scene-word:o-caracol", "scene-word:a-folha", "scene-word:a-relva")), NativeSet("collection:scene-set-rain", "Под дождём", listOf("scene-word:a-nuvem", "scene-word:a-chuva", "scene-word:o-vento", "scene-word:o-guarda-chuva", "scene-word:o-casaco", "scene-word:as-botas", "scene-word:a-poca")), NativeSet("collection:scene-set-weather", "После дождя", listOf("scene-word:a-nuvem", "scene-word:o-vento", "scene-word:a-chuva", "scene-word:o-guarda-chuva", "scene-word:o-casaco", "scene-word:as-botas", "scene-word:a-poca")), NativeSet("collection:scene-set-park", "В парке", listOf("scene-word:o-parque", "scene-word:o-passaro", "scene-word:a-arvore", "scene-word:o-banco", "scene-word:a-bicicleta", "scene-word:o-cao", "scene-word:a-bola")))),
    NativeTopic("topic:animals", "Животные", listOf(NativeSet("collection:scene-set-garden", "В саду", listOf("scene-word:a-arvore", "scene-word:a-borboleta", "scene-word:a-abelha", "scene-word:a-flor", "scene-word:o-caracol", "scene-word:a-folha", "scene-word:a-relva")), NativeSet("collection:scene-set-farm", "На ферме", listOf("scene-word:a-vaca", "scene-word:o-cavalo", "scene-word:o-gato", "scene-word:o-porco", "scene-word:a-ovelha", "scene-word:a-galinha", "scene-word:o-pato")), NativeSet("collection:scene-set-park", "В парке", listOf("scene-word:o-parque", "scene-word:o-passaro", "scene-word:a-arvore", "scene-word:o-banco", "scene-word:a-bicicleta", "scene-word:o-cao", "scene-word:a-bola")))),
    NativeTopic("topic:city", "Город и дорога", listOf(NativeSet("collection:scene-set-street", "На нашей улице", listOf("scene-word:a-casa", "scene-word:a-escola", "scene-word:a-loja", "scene-word:a-farmacia", "scene-word:o-cafe", "scene-word:a-rua", "scene-word:o-autocarro", "scene-word:a-paragem")), NativeSet("collection:scene-set-park", "В парке", listOf("scene-word:o-parque", "scene-word:o-passaro", "scene-word:a-arvore", "scene-word:o-banco", "scene-word:a-bicicleta", "scene-word:o-cao", "scene-word:a-bola")), NativeSet("collection:vocabulary-lesson:city", "Город и дорога", listOf("general-vocabulary:noun:praca", "general-vocabulary:noun:avenida", "general-vocabulary:noun:ponte", "general-vocabulary:noun:estacao")))),
    NativeTopic("topic:school", "Школа", listOf(NativeSet("collection:scene-set-school", "Собираемся в школу", listOf("scene-word:a-mochila", "scene-word:o-caderno", "scene-word:o-lapis", "scene-word:a-caneta", "scene-word:o-livro", "scene-word:a-borracha", "scene-word:a-regua")), NativeSet("collection:pairs-school-instructions", "Инструкции на уроке", listOf("v0083", "v0062", "v0242", "v0258", "v0682", "v0379", "v0154", "v0091")))),
    NativeTopic("topic:work", "Работа и встречи", listOf(NativeSet("collection:vocabulary-lesson:work", "Работа и встречи", listOf("general-vocabulary:noun:emprego", "general-vocabulary:noun:escritorio", "general-vocabulary:noun:empresa", "general-vocabulary:noun:reuniao", "general-vocabulary:noun:salario", "general-vocabulary:noun:cliente")))),
    NativeTopic("topic:health", "Здоровье и самочувствие", listOf(NativeSet("collection:vocabulary-lesson:health", "Здоровье и самочувствие", listOf("general-vocabulary:verb:respirar", "general-vocabulary:verb:relaxar", "general-vocabulary:verb:tossir", "general-vocabulary:verb:espirrar", "general-vocabulary:verb:curar", "general-vocabulary:verb:sarar")))),
    NativeTopic("topic:people", "Люди и состояния", listOf(NativeSet("collection:vocabulary-lesson:people", "Люди и состояния", listOf("general-vocabulary:adjective:feliz", "general-vocabulary:adjective:ocupado", "general-vocabulary:adjective:livre", "general-vocabulary:adjective:nervoso", "general-vocabulary:adjective:gentil", "general-vocabulary:adjective:educado"))))
)

val nativeUsages = listOf(
    NativeUsage("usage:school-materials-in-context", "Школьные вещи во фразах", "Посмотри, как знакомые слова меняются внутри обычных школьных фраз, а затем дополни похожие предложения.", listOf("collection:scene-set-school"), listOf(Example("O livro está na mochila.", "Книга находится в рюкзаке."), Example("Tenho um lápis e um caderno.", "У меня есть карандаш и тетрадь."), Example("Há uma caneta ao lado da régua.", "Рядом с линейкой лежит ручка."), Example("Escrevo no caderno com a caneta.", "Я пишу в тетради ручкой.")), listOf(NativeActivity("usage-cloze:school-read-book", "Что открывают, чтобы читать?", "Para ler, abro ", ".", listOf(AnswerOption("school-read-book", "o livro"), AnswerOption("school-read-ruler", "a régua"), AnswerOption("school-read-eraser", "a borracha")), "school-read-book", "Para ler, abro o livro. — Чтобы читать, я открываю книгу."), NativeActivity("usage-cloze:school-measure-ruler", "Чем измеряют длину?", "Para medir, uso ", ".", listOf(AnswerOption("school-measure-ruler", "a régua"), AnswerOption("school-measure-pen", "a caneta"), AnswerOption("school-measure-notebook", "o caderno")), "school-measure-ruler", "Para medir, uso a régua. — Чтобы измерить, я использую линейку."), NativeActivity("usage-cloze:school-erase", "Чем стирают написанное карандашом?", "Para apagar, uso ", ".", listOf(AnswerOption("school-erase-eraser", "a borracha"), AnswerOption("school-erase-pencil", "o lápis"), AnswerOption("school-erase-book", "o livro")), "school-erase-eraser", "Para apagar, uso a borracha. — Чтобы стереть, я использую ластик."), NativeActivity("usage-cloze:school-store", "Куда складывают школьные принадлежности?", "Guardo os materiais ", ".", listOf(AnswerOption("school-store-backpack", "na mochila"), AnswerOption("school-store-notebook", "no caderno"), AnswerOption("school-store-ruler", "na régua")), "school-store-backpack", "Guardo os materiais na mochila. — Я храню школьные принадлежности в рюкзаке."), NativeActivity("usage-cloze:school-write", "Дополни фразу про работу в тетради.", "Escrevo ", " com a caneta.", listOf(AnswerOption("school-write-notebook", "no caderno"), AnswerOption("school-write-backpack", "na mochila"), AnswerOption("school-write-ruler", "na régua")), "school-write-notebook", "Escrevo no caderno com a caneta. — Я пишу в тетради ручкой.")))
)

val nativeRelatedLessons = listOf(
    NativeRelatedLesson("lesson:a1-1:locate-object", "Где находится предмет", "Сначала найдите знакомый предмет, затем определите, где он находится: внутри, сверху, под чем-то или рядом.", listOf(Example("Onde está o gato?", "Где кот?"), Example("O gato está na caixa.", "Кот в коробке.")), listOf(Example("dentro de", "внутри"), Example("em cima de", "на / сверху"), Example("debaixo de", "под"), Example("ao lado de", "рядом с"), Example("no / na", "в / на + известный предмет")), NativeActivity("exercise:space:independent", "Прочитайте фразу и выберите, где должен быть кот: O gato está debaixo da mesa.", "", "", listOf(AnswerOption("inside", "в коробке"), AnswerOption("on", "на столе"), AnswerOption("under", "под столом")), "under", "")),
    NativeRelatedLesson("lesson:a1-1:possession-and-presence", "TER и HÁ", "TER говорит, что есть у конкретного человека или предмета. HÁ — что вообще есть в комнате. HÁ не меняется, даже если предметов несколько.", listOf(Example("A Rita tem uma chave.", "У Риты есть ключ."), Example("Há três livros na mesa.", "На столе есть три книги.")), listOf(Example("a sala — as salas", "комната / гостиная"), Example("a cadeira — as cadeiras", "стул — стулья"), Example("a cama — as camas", "кровать — кровати"), Example("o quarto — os quartos", "спальня — спальни"), Example("o armário — os armários", "шкаф — шкафы"), Example("o copo — os copos", "стакан — стаканы")), NativeActivity("exercise:ter-ha:independent", "В комнате два стула, но мы не говорим, чьи они. Какая фраза подходит?", "", "", listOf(AnswerOption("ha", "Há duas cadeiras na sala."), AnswerOption("tem", "Tem duas cadeiras na sala.")), "ha", ""))
)

val nativeVerbForms = listOf(
    NativeVerbForms("falar", "falar", "говорить", listOf("falo", "falas", "fala", "falamos", "falam", "falam")),
    NativeVerbForms("estudar", "estudar", "учиться", listOf("estudo", "estudas", "estuda", "estudamos", "estudam", "estudam")),
    NativeVerbForms("trabalhar", "trabalhar", "работать", listOf("trabalho", "trabalhas", "trabalha", "trabalhamos", "trabalham", "trabalham")),
    NativeVerbForms("reparar", "reparar", "ремонтировать", listOf("reparo", "reparas", "repara", "reparamos", "reparam", "reparam")),
    NativeVerbForms("montar", "montar", "собирать", listOf("monto", "montas", "monta", "montamos", "montam", "montam")),
    NativeVerbForms("criar", "criar", "создавать", listOf("crio", "crias", "cria", "criamos", "criam", "criam")),
    NativeVerbForms("comer", "comer", "есть", listOf("como", "comes", "come", "comemos", "comem", "comem")),
    NativeVerbForms("beber", "beber", "пить", listOf("bebo", "bebes", "bebe", "bebemos", "bebem", "bebem")),
    NativeVerbForms("aprender", "aprender", "учить", listOf("aprendo", "aprendes", "aprende", "aprendemos", "aprendem", "aprendem")),
    NativeVerbForms("viver", "viver", "жить", listOf("vivo", "vives", "vive", "vivemos", "vivem", "vivem")),
    NativeVerbForms("crescer", "crescer", "расти", listOf("cresço", "cresces", "cresce", "crescemos", "crescem", "crescem")),
    NativeVerbForms("compreender", "compreender", "понимать", listOf("compreendo", "compreendes", "compreende", "compreendemos", "compreendem", "compreendem")),
    NativeVerbForms("partir", "partir", "уезжать", listOf("parto", "partes", "parte", "partimos", "partem", "partem")),
    NativeVerbForms("abrir", "abrir", "открывать", listOf("abro", "abres", "abre", "abrimos", "abrem", "abrem")),
    NativeVerbForms("assistir", "assistir", "смотреть", listOf("assisto", "assistes", "assiste", "assistimos", "assistem", "assistem")),
    NativeVerbForms("descobrir", "descobrir", "открывать, обнаруживать", listOf("descubro", "descobres", "descobre", "descobrimos", "descobrem", "descobrem")),
    NativeVerbForms("decidir", "decidir", "решать", listOf("decido", "decides", "decide", "decidimos", "decidem", "decidem")),
    NativeVerbForms("transmitir", "transmitir", "передавать", listOf("transmito", "transmites", "transmite", "transmitimos", "transmitem", "transmitem")),
    NativeVerbForms("ir", "ir", "идти", listOf("vou", "vais", "vai", "vamos", "vão", "vão")),
    NativeVerbForms("fazer", "fazer", "делать", listOf("faço", "fazes", "faz", "fazemos", "fazem", "fazem")),
    NativeVerbForms("ter", "ter", "иметь", listOf("tenho", "tens", "tem", "temos", "têm", "têm")),
    NativeVerbForms("ficar", "ficar", "находиться; оставаться", listOf("fico", "ficas", "fica", "ficamos", "ficam", "ficam")),
    NativeVerbForms("dizer", "dizer", "говорить", listOf("digo", "dizes", "diz", "dizemos", "dizem", "dizem")),
    NativeVerbForms("ser", "ser", "быть: кто или что", listOf("sou", "és", "é", "somos", "são", "são")),
    NativeVerbForms("estar", "estar", "быть: как или где", listOf("estou", "estás", "está", "estamos", "estão", "estão"))
)
